// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TelezoncalldeatilsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void telezoncalldeatils() {
    // Test name: telezon call deatils
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8082/calls |  | 
    driver.get("http://localhost:8082/calls");
    // 2 | setWindowSize | 789x912 |  | 
    driver.manage().window().setSize(new Dimension(789, 912));
    // 3 | click | id=cid |  | 
    driver.findElement(By.id("cid")).click();
    // 4 | type | id=cid | 1010 | 
    driver.findElement(By.id("cid")).sendKeys("1010");
    // 5 | click | id=fromName |  | 
    driver.findElement(By.id("fromName")).click();
    // 6 | select | id=fromName | label=fawaaaz | 
    {
      WebElement dropdown = driver.findElement(By.id("fromName"));
      dropdown.findElement(By.xpath("//option[. = 'fawaaaz']")).click();
    }
    // 7 | click | id=toName |  | 
    driver.findElement(By.id("toName")).click();
    // 8 | select | id=toName | label=bijosh | 
    {
      WebElement dropdown = driver.findElement(By.id("toName"));
      dropdown.findElement(By.xpath("//option[. = 'bijosh']")).click();
    }
    // 9 | click | id=usedDuration |  | 
    driver.findElement(By.id("usedDuration")).click();
    // 10 | type | xpath=//input[@id='usedDuration'] | 10 | 
    driver.findElement(By.xpath("//input[@id=\'usedDuration\']")).sendKeys("10");
    // 11 | click | xpath=//button[contains(.,'Add Call')] |  | 
    driver.findElement(By.xpath("//button[contains(.,\'Add Call\')]")).click();
    // 12 | click | xpath=//input[@id='cid'] |  | 
    driver.findElement(By.xpath("//input[@id=\'cid\']")).click();
    // 13 | type | xpath=//input[@id='cid'] | 2020 | 
    driver.findElement(By.xpath("//input[@id=\'cid\']")).sendKeys("2020");
    // 14 | click | xpath=//select[@id='fromName'] |  | 
    driver.findElement(By.xpath("//select[@id=\'fromName\']")).click();
    // 15 | select | id=fromName | label=bijosh | 
    {
      WebElement dropdown = driver.findElement(By.id("fromName"));
      dropdown.findElement(By.xpath("//option[. = 'bijosh']")).click();
    }
    // 16 | click | xpath=//select[@id='toName'] |  | 
    driver.findElement(By.xpath("//select[@id=\'toName\']")).click();
    // 17 | click | xpath=//select[@id='toName'] |  | 
    driver.findElement(By.xpath("//select[@id=\'toName\']")).click();
    // 18 | click | xpath=//form[@action='/calls'] |  | 
    driver.findElement(By.xpath("//form[@action=\'/calls\']")).click();
    // 19 | click | xpath=//input[@id='usedDuration'] |  | 
    driver.findElement(By.xpath("//input[@id=\'usedDuration\']")).click();
    // 20 | type | xpath=//input[@id='usedDuration'] | 20 | 
    driver.findElement(By.xpath("//input[@id=\'usedDuration\']")).sendKeys("20");
    // 21 | click | xpath=//button[contains(.,'Add Call')] |  | 
    driver.findElement(By.xpath("//button[contains(.,\'Add Call\')]")).click();
  }
}
