// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TelezonprepaidTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void telezonprepaid() {
    // Test name: telezon prepaid
    // Step # | name | target | value | comment
    // 1 | open | /prepaid |  | 
    driver.get("http://localhost:8082/customers/prepaid");
    // 2 | setWindowSize | 789x912 |  | 
    driver.manage().window().setSize(new Dimension(789, 912));
    // 3 | click | xpath=//input[@id='planId'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planId\']")).click();
    // 4 | type | xpath=//input[@id='planId'] | 101 | 
    driver.findElement(By.xpath("//input[@id=\'planId\']")).sendKeys("101");
    // 5 | click | xpath=//input[@id='planName'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planName\']")).click();
    // 6 | type | xpath=//input[@id='planName'] | plan111 | 
    driver.findElement(By.xpath("//input[@id=\'planName\']")).sendKeys("plan111");
    // 7 | click | xpath=//input[@id='planPrice'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planPrice\']")).click();
    // 8 | type | xpath=//input[@id='planPrice'] | 111 | 
    driver.findElement(By.xpath("//input[@id=\'planPrice\']")).sendKeys("111");
    // 9 | click | xpath=//input[@id='planLimit'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planLimit\']")).click();
    // 10 | type | xpath=//input[@id='planLimit'] | 50 | 
    driver.findElement(By.xpath("//input[@id=\'planLimit\']")).sendKeys("50");
    // 11 | click | xpath=//input[@id='duration'] |  | 
    driver.findElement(By.xpath("//input[@id=\'duration\']")).click();
    // 12 | type | xpath=//input[@id='duration'] | 28 | 
    driver.findElement(By.xpath("//input[@id=\'duration\']")).sendKeys("28");
    // 13 | click | xpath=//button[contains(.,'Add Prepaid Plan')] |  | 
    driver.findElement(By.xpath("//button[contains(.,\'Add Prepaid Plan\')]")).click();
  }
}
