// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TelezoncustomerdetailsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void telezoncustomerdetails() {
    // Test name: telezon customer details
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8082/customers |  | 
    driver.get("http://localhost:8082/customers");
    // 2 | setWindowSize | 789x912 |  | 
    driver.manage().window().setSize(new Dimension(789, 912));
    // 3 | click | id=id |  | 
    driver.findElement(By.id("id")).click();
    // 4 | type | id=id | 345 | 
    driver.findElement(By.id("id")).sendKeys("345");
    // 5 | click | xpath=//input[@id='name'] |  | 
    driver.findElement(By.xpath("//input[@id=\'name\']")).click();
    // 6 | type | xpath=//input[@id='name'] | prabha | 
    driver.findElement(By.xpath("//input[@id=\'name\']")).sendKeys("prabha");
    // 7 | click | xpath=//input[@id='email'] |  | 
    driver.findElement(By.xpath("//input[@id=\'email\']")).click();
    // 8 | type | xpath=//input[@id='email'] | prabha@gmail.com | 
    driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("prabha@gmail.com");
    // 9 | click | xpath=//input[@id='phoneNumber'] |  | 
    driver.findElement(By.xpath("//input[@id=\'phoneNumber\']")).click();
    // 10 | type | xpath=//input[@id='phoneNumber'] | 24638 | 
    driver.findElement(By.xpath("//input[@id=\'phoneNumber\']")).sendKeys("24638");
    // 11 | click | xpath=//input[@id='postpaidRadio'] |  | 
    driver.findElement(By.xpath("//input[@id=\'postpaidRadio\']")).click();
    // 12 | click | xpath=//select[@id='postpaidPlan'] |  | 
    driver.findElement(By.xpath("//select[@id=\'postpaidPlan\']")).click();
    // 13 | select | id=postpaidPlan | label=plan222 | 
    {
      WebElement dropdown = driver.findElement(By.id("postpaidPlan"));
      dropdown.findElement(By.xpath("//option[. = 'plan222']")).click();
    }
    // 14 | click | xpath=//button[contains(.,'Add Customer')] |  | 
    driver.findElement(By.xpath("//button[contains(.,\'Add Customer\')]")).click();
    // 15 | click | xpath=//button[@onclick="window.location.href='/customers?filter=prepaid'"] |  | 
    driver.findElement(By.xpath("//button[@onclick=\"window.location.href=\'/customers?filter=prepaid\'\"]")).click();
    // 16 | click | xpath=//button[@onclick="window.location.href='/customers?filter=postpaid'"] |  | 
    driver.findElement(By.xpath("//button[@onclick=\"window.location.href=\'/customers?filter=postpaid\'\"]")).click();
    // 17 | click | xpath=//button[@onclick="window.location.href='/customers?filter=all'"] |  | 
    driver.findElement(By.xpath("//button[@onclick=\"window.location.href=\'/customers?filter=all\'\"]")).click();
  }
}
