// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TelezonpostpaidTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void telezonpostpaid() {
    // Test name: telezon postpaid
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8082/postpaid |  | 
    driver.get("http://localhost:8082/postpaid");
    // 2 | setWindowSize | 790x912 |  | 
    driver.manage().window().setSize(new Dimension(790, 912));
    // 3 | click | xpath=//input[@id='planId'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planId\']")).click();
    // 4 | type | xpath=//input[@id='planId'] | 201 | 
    driver.findElement(By.xpath("//input[@id=\'planId\']")).sendKeys("201");
    // 5 | click | xpath=//input[@id='planName'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planName\']")).click();
    // 6 | type | xpath=//input[@id='planName'] | plan222 | 
    driver.findElement(By.xpath("//input[@id=\'planName\']")).sendKeys("plan222");
    // 7 | click | xpath=//input[@id='planPrice'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planPrice\']")).click();
    // 8 | type | xpath=//input[@id='planPrice'] | 222 | 
    driver.findElement(By.xpath("//input[@id=\'planPrice\']")).sendKeys("222");
    // 9 | click | xpath=//input[@id='planBillCycle'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planBillCycle\']")).click();
    // 10 | type | xpath=//input[@id='planBillCycle'] | 45 | 
    driver.findElement(By.xpath("//input[@id=\'planBillCycle\']")).sendKeys("45");
    // 11 | click | xpath=//input[@id='planDataCap'] |  | 
    driver.findElement(By.xpath("//input[@id=\'planDataCap\']")).click();
    // 12 | type | xpath=//input[@id='planDataCap'] | 60 | 
    driver.findElement(By.xpath("//input[@id=\'planDataCap\']")).sendKeys("60");
    // 13 | click | xpath=//button[contains(.,'Add Postpaid Plan')] |  | 
    driver.findElement(By.xpath("//button[contains(.,\'Add Postpaid Plan\')]")).click();
  }
}
